# Generated by Django 5.1.1 on 2025-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Diploma', 'Diploma'), ('Certification', 'Certification')], max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('syllabus', models.TextField()),
                ('eligibility', models.TextField()),
            ],
        ),
    ]
